### ISSUE TITLE
INFO Predicate does not have an arity defined

### ISSUE THREAD

**Issue by jefft0** [ontologyportal/sigmakee#11]
When I load the constituents in Sigma, I get a blizzard of log messages in the Java console like the ones shown below. Do termFormat and instance (and many others) need to have their arity defined? If yes, should SUMO be updated to define them? If not, then is this log message necessary?

    INFO in PredVarInst.hasCorrectArityRecurse(): Predicate termFormat does not have an arity defined in KB, can't get the arity number!
    (termFormat EnglishLanguage Interviewing "interviewing")
    INFO in PredVarInst.hasCorrectArityRecurse(): Predicate instance does not have an arity defined in KB, can't get the arity number!
    (instance relatedInternalConcept EquivalenceRelation)

**Comment by arademaker** [comment]
Possible bug in the code, in =Merge.kif= we have both

```
(instance instance BinaryPredicate)
(instance termFormat TernaryPredicate)
```

**Comment by jefft0** [comment]
Interesting. I'm also getting the log message for subclass, distance, and others. But these also have definitions:

    (instance subclass BinaryPredicate)
    (instance distance TernaryPredicate)

**Comment by apease** [comment]
Hi Alexandre,
   I believe this is correct.  &%instance is binary and &%termFormat is 
ternary since it takes a term, a printable string for that term and a 
language in which it is expressed.

Adam


On 06/18/2016 07:22 AM, Alexandre Rademaker wrote:
> Possible bug in the code, in =Merge.kif= we have both
>
> |(instance instance BinaryPredicate) (instance termFormat TernaryPredicate) |
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ontologyportal/sigmakee/issues/11#issuecomment-226945029>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACBvHfElVBxqd7MgZiMtMvs4gyyhUOdpks5qM_8qgaJpZM4I49Ea>.
>

-- 
-------------------
Adam Pease
http://www.ontologyportal.org
http://www.articulatesoftware.com
http://www.adampease.org

**Comment by arademaker** [comment]
Yes, I agree. But how to explain the error reported above?

**Comment by apease** [comment]
not sure why that error appears since 

(instance termFormat TernaryPredicate)	  ; Merge.kif 381-381
(instance instance BinaryPredicate)	; Merge.kif 81-81

**Comment by apease** [comment]
ah, probably because of the cache="no" issue.  If you have time, please 
verify that these messages no longer appear when you have cache="yes" in 
your config.xml

On 06/18/2016 07:06 AM, Jeff Thompson wrote:
> When I load the constituents in Sigma, I get a blizzard of log messages
> in the Java console like the ones shows below. Do termFormat and
> instance (and many others) need to have their arity defined? If yes,
> should SUMO be updated to define them? If not, then is this log message
> necessary?
>
> |INFO in PredVarInst.hasCorrectArityRecurse(): Predicate termFormat does
> not have an arity defined in KB, can't get the arity number! (termFormat
> EnglishLanguage Interviewing "interviewing") INFO in
> PredVarInst.hasCorrectArityRecurse(): Predicate instance does not have
> an arity defined in KB, can't get the arity number! (instance
> relatedInternalConcept EquivalenceRelation) |
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ontologyportal/sigmakee/issues/11>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ACBvHQPNLIpoJM0iGqjzFvNsE3aJJkZiks5qM_tzgaJpZM4I49Ea>.
>

-- 
-------------------
Adam Pease
http://www.ontologyportal.org
http://www.articulatesoftware.com
http://www.adampease.org

**Comment by jefft0** [comment]
Yes, the messages no longer appear when "cache"="yes". Should the arity check be skipped if KBcache is empty?

**Comment by apease** [comment]
yes, that sounds sensible

On 06/19/2016 02:42 AM, Jeff Thompson wrote:
> Yes, the messages no longer appear when "cache"="yes". Should the arity
> check be skipped if KBcache is empty?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ontologyportal/sigmakee/issues/11#issuecomment-226988352>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACBvHV5GCBzJCbvTv6U8msWYJSkXeBKFks5qNQ8EgaJpZM4I49Ea>.
>

-- 
-------------------
Adam Pease
http://www.ontologyportal.org
http://www.articulatesoftware.com
http://www.adampease.org

**Comment by arademaker** [comment]
This solution closes this issue?

**Comment by jefft0** [comment]
Take a look at pull request https://github.com/ontologyportal/sigmakee/pull/14 which would prevent the blizzard if "cache" is "no".

**Comment by jefft0** [comment]
The pull request is merged.
