### ISSUE TITLE
Can't use E to prove (instance causes Predicate)

### ISSUE THREAD

**Issue by jefft0** [ontologyportal/sigmakee#18]
To reproduce: Run Sigma with E version 1.9. In the Manifest, load Merge.kif. In the Ask screen, query the following:

    (instance causes Predicate)

Expected result: Since Merge.kif has `(instance causes BinaryPredicate)` and `(subclass BinaryPredicate Predicate)` it should be able to find a proof for the query.

Actual result: It does not find a proof.

Analysis: Here is a message from Adam: This statement should be trivial because it should be cached.  Yet in SUMO.tptp I find only 

    fof(kb_SUMO_732,axiom,(( s__instance(s__causes__m,s__AsymmetricRelation) ))).
    fof(kb_SUMO_733,axiom,(( s__instance(s__causes__m,s__BinaryPredicate) ))).
    fof(kb_SUMO_734,axiom,(( s__instance(s__causesProposition__m,s__AsymmetricRelation) ))).
    fof(kb_SUMO_735,axiom,(( s__instance(s__causesProposition__m,s__BinaryPredicate) ))).
    fof(kb_SUMO_736,axiom,(( s__instance(s__causesSubclass__m,s__AsymmetricRelation) ))).
    fof(kb_SUMO_737,axiom,(( s__instance(s__causesSubclass__m,s__BinaryPredicate) ))).

and yet since

    (subclass BinaryPredicate Predicate)    Merge.kif 2926-2926

we should see

    ( s__instance(s__causes__m,s__Predicate) )

so something is wrong with caching.  However, E should also be able to make the one step inference to compute this.  Two things to investigate.

**Comment by apease** [comment]
The cache holds the correct information:

KBcache.main(): parents of BinaryPredicate: [Entity, Relation, InheritableRelation, Abstract, BinaryRelation, Predicate]
KBcache.main(): parents of causes: [AsymmetricRelation, Entity, Relation, AntisymmetricRelation, InheritableRelation, Abstract, IrreflexiveRelation, BinaryPredicate, BinaryRelation, Predicate]

So, somehow this information from the cache isn't getting into the TPTP file...

**Comment by apease** [comment]
somewhere along the line I lost the call to KBcache.writeCacheFile() so the cache wasn't being written.  But an additional problem is that we're not writing cache statements involve "instance",which was an oversight that probably occurred when I rewrote caching.  That's the next thing to fix.

**Comment by apease** [comment]
Fixed and will upload code shortly. Cached instance relations are now written correctly and the proof is found


1.	(instance causes Predicate)	[KB]	instance causes and Predicate
2.	(not
    (instance causes Predicate))	4	instance causes and Predicate
3.	True	2 1	True

**Comment by apease** [comment]
fixed committed, issue can be closed once independently replicated

**Comment by jefft0** [comment]
Great! Works for me. Thanks for the quick fix. I'll close the issue.
