### ISSUE TITLE
Title bar reordering

### ISSUE THREAD

**Issue by msvarny** [ontologyportal/sigmakee#21]
I have suggestion on a tiny change that would help me and hopefully other users a lot: would it be possible to reorder the informations in Sigma pages' title?

Now the title of  a browser running sigma shows "Knowledge base Browser - [KB Term] - [Browser name]". When multiple tabs with different terms are opened it becomes increasingly difficult to navigate them with each new tab opened.

I would prefer if the KB Term would be in the first place. so that it's possible to see at first glance which Term is opened in which tab.

**Comment by apease** [comment]
good idea!  I'll try to do this soon

**Comment by apease** [comment]
I've pushed the fix to github if you want to update, recompile and try

**Comment by msvarny** [comment]
Works great! Thanks.
