### ISSUE TITLE
Can't use E with SUMO.tptp (TPTP FOL)

### ISSUE THREAD

**Issue by fcbr** [ontologyportal/sigmakee#4]
1. Export all of SUMO as TPTPFOL
2. Add the following line to the SUMO.tptp file:

```
fof(conj1,conjecture,$false).
```

3. Execute E as follows:

```
eprover --auto --tptp3-in -l 4 KBs/SUMO.tptp
```

PROBLEM:

E terminates with a failure:

```
# Failure: Out of unprocessed clauses!
```

Full output follows:

```
# SinE strategy is gf500_h_gu_R04_F100_L20000
     1 : conj:~$true : initial("KBs/SUMO.tptp", conj1)
     2 : neg:~(~$true) : assume_negation(1)
     3 : neg:$true : fof_simplification(2)
     4 : neg:[++$true] : split_conjunct(3)

# Auto-Ordering is analysing problem.
# Problem is type UUPFGFFSF00SS
# Auto-mode selected ordering type KBO6
# Auto-mode selected ordering precedence scheme <invfreq>
# Auto-mode selected weight ordering scheme <invfreqrank>
#
# Auto-Heuristic is analysing problem.
# Problem is type UUPFGFFSF00SS
# Auto-Mode selected heuristic G_E___208_C18_F1_SE_CS_SP_PS_S0Y
# and selection function SelectMaxLComplexAvoidPosPred.
#
# No equality, disabling AC handling.
#
# Initializing proof state
# Presaturation interreduction done

# Failure: Out of unprocessed clauses!
# SZS status GaveUp
# Parsed axioms                        : 26445
# Removed by relevancy pruning/SinE    : 26444
# Initial clauses                      : 1
# Removed in clause preprocessing      : 1
# Initial clauses in saturation        : 0
# Processed clauses                    : 0
# ...of these trivial                  : 0
# ...subsumed                          : 0
# ...remaining for further processing  : 0
# Other redundant clauses eliminated   : 0
# Clauses deleted for lack of memory   : 0
# Backward-subsumed                    : 0
# Backward-rewritten                   : 0
# Generated clauses                    : 0
# ...of the previous two non-trivial   : 0
# Contextual simplify-reflections      : 0
# Paramodulations                      : 0
# Factorizations                       : 0
# Equation resolutions                 : 0
# Current number of processed clauses  : 0
#    Positive orientable unit clauses  : 0
#    Positive unorientable unit clauses: 0
#    Negative unit clauses             : 0
#    Non-unit-clauses                  : 0
# Current number of unprocessed clauses: 0
# ...number of literals in the above   : 0
# Clause-clause subsumption calls (NU) : 0
# Rec. Clause-clause subsumption calls : 0
# Non-unit clause-clause subsumptions  : 0
# Unit Clause-clause subsumption calls : 0
# Rewrite failures with RHS unbound    : 0
# BW rewrite match attempts            : 0
# BW rewrite match successes           : 0
# Condensation attempts                : 0
# Condensation successes               : 0
```

**Comment by arademaker** [comment]
@fcbr or @apease , can you describe (or point to the doc) how to generate the TPTP, that is, what is the command line for exporting SUMO to TPTP formats.

**Comment by apease** [comment]
Hi Alexandre,
   You'll need to use the Sigma web interface.  Go to the Manifest page 
and then select SaveAs TPTPFOL.
   If your KB is called "SUMO" and you have set up your SIGMA_HOME and 
config.xml you may be able to invoke on the command line with something like

java -classpath 
/home/apease/workspace/sigmakee/build/classes:/home/apease/workspace/sigmakee/lib/guava-15.0.jar 
com.articulate.sigma.SUMOKBtoTPTPKB

   We could also add a proper Unix-style command line interface to that 
class with command line syntax and options.

Adam

On 02/19/2016 01:42 PM, Alexandre Rademaker wrote:
> @fcbr <https://github.com/fcbr> or @apease <https://github.com/apease> ,
> can you describe (or point to the doc) how to generate the TPTP, that
> is, what is the command line for exporting SUMO to TPTP formats.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ontologyportal/sigmakee/issues/4#issuecomment-186420035>.
>

-- 
-------------------
Adam Pease
http://www.ontologyportal.org
http://www.articulatesoftware.com
http://www.adampease.org

**Comment by fcbr** [comment]
this seems to be working now, but see  issues #5 #6 #7
