### ISSUE TITLE
TPTP transformation is broken

### ISSUE THREAD

**Issue by arademaker** [ontologyportal/sigmakee#45]
```
% f: (<=> (exists (?BUILD) (and (instance ?BUILD Constructing) (result ?BUILD ?ARTIFACT))) (instance ?ARTIFACT StationaryArtifact))
% 31 of 34586 from file /Users/ar/workspace/sumo/Merge.kif at line 12717
% not higher order
fof(kb_SUMO_29,axiom,(( ( ! [V__ARTIFACT] : (() => ((? [V__BUILD] : (s__instance(V__BUILD,s__Constructing) & s__result(V__BUILD,V__ARTIFACT))) <=> s__instance(V__ARTIFACT,s__StationaryArtifact))) ) ))).
```

Vampire reports 

```
$ ~/work/vampire/vampire --mode casc -t 300 sumo/SUMO.tptp
% Exception at proof search level
Parsing Error on line 125
formula or term expected at position 16473 (text: ))
```

Note the `()` on the left side of the first implication. I suspect that some code shared between TPTP and TFF transformations once adapted to TFF, broke the TPTP transformation.

**Comment by apease** [comment]
added a jUnit test TesttptpParseSUOKIFString7() in  com.articulate.sigma.trans.SUMOformulaToTPTPformulaTest and it passes so now to figure out why it only works in isolation but an error happens when processing many statements

**Comment by apease** [comment]
fixed in commit https://github.com/ontologyportal/sigmakee/commit/0cf527e1279676a3fb1c832b8ab586c670ccd758
