### ISSUE TITLE
MAC OS install

### ISSUE THREAD

**Issue by jmugan** [ontologyportal/sigmakee#57]
A couple snags I found in https://github.com/ontologyportal/sigmakee/blob/master/INSTALL.MacOS

In line 46, I needed to add `-L` to be `curl -O -L 'http://wordnetcode.princeton.edu/3.0/WordNet-3.0.tar.gz'`

On line 59, `.sigmakee` has no `config.xml` file. Do you mean `workspace/sigmakee/config.xml`?

**Comment by apease** [comment]
yes, it should be workspace/sigmakee/config.xml .  I'll change the script to use absolute paths, as that must have been the cause of the confusion

**Comment by jmugan** [comment]
I'm having trouble with the classpath as well. After the build, it looks like the classes are in `/Users/jmugan/sumo/workspace/sigmakee/build/classes` but line 21 indicates they should come from `export SIGMA_HOME=/Users/user/.sigmakee`

**Comment by apease** [comment]
you need to edit the SIGMA_HOME and all other environment variables to conform to your paths.  You'll have two top level directories for Sigma - one to hold the code that gets compiled and another to hold all the data used by the application.  The checked out code for you should be /Users/jmugan/sumo/workspace/sigmakee (and you'll also check out sumo as /Users/jmugan/sumo/workspace/sumo ) The application data for the running sigma would ideally be at /Users/jmugan/.sigmakee and that would be the value of your SIGMA_HOME

**Comment by jmugan** [comment]
How do files get into `/Users/jmugan/sumo/.sigmakee/KBs`? When I run it, the first error I get is `Error in KIF.readFile():  error file /Users/jmugan/sumo/.sigmakee/KBs/english_format.kifdoes not exist` It's right. There is nothing there.

**Comment by apease** [comment]
sorry it looks like the Mac install instructions are missing steps that are in the linux instructions.  I'll have to take some time to review and correct them

**Comment by jmugan** [comment]
Ah,I'll go into the Linux instructions and see what steps I may have missed. Thanks!

**Comment by jmugan** [comment]
Looks like
`mkdir ~/.sigmakee/KBs/`
`cp -R ~/workspace/sumo/* ~/.sigmakee/KBs/`
`cp WordNet-3.0/dict/* ~/.sigmakee/KBs/WordNetMappings/`

**Comment by apease** [comment]
that's right if you made your SIGMA_HOME /Users/jmugan/.sigmakee
