### ISSUE TITLE
Rename file "*.awk"?

### ISSUE THREAD

**Issue by jefft0** [ontologyportal/sigmakee#8]
There is a file "*.awk" in this folder: https://github.com/ontologyportal/sigmakee/blob/master/native-installers/debian/dependencies/files/opt/sigma/E/PYTHON/

I can't git clone the repository on Windows because there's no way to allow "*" in a filename. Is there some way to rename or remove this file?

**Comment by apease** [comment]
not sure what this was for, but it certainly looks bogus so I've removed it

On 06/14/2016 02:45 AM, Jeff Thompson wrote:
> There is a file "*.awk" in this folder:
> https://github.com/ontologyportal/sigmakee/blob/master/native-installers/debian/dependencies/files/opt/sigma/E/PYTHON/
>
> I can't git clone the repository on Windows because there's no way to
> allow "*" in a filename. Is there some way to rename or remove this file?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ontologyportal/sigmakee/issues/8>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ACBvHZX9PdWZQi9Pcof2l0pyA9Exexcgks5qLnhRgaJpZM4I1JBD>.
>

-- 
-------------------
Adam Pease
http://www.ontologyportal.org
http://www.articulatesoftware.com
http://www.adampease.org
