### ISSUE TITLE
Prenexifier methods missing return statements.

### ISSUE THREAD

**Issue by jefft0** [ontologyportal/sigmakee#9]
The methods in Prenexifier have a return type for Formula, but are missing return statements. My Java compiler won't compile it. (I'd offer a pull request, but I don't know what it's supposed to do.)
https://github.com/ontologyportal/sigmakee/blob/master/src/java/com/articulate/sigma/Prenexifier.java

**Comment by apease** [comment]
sorry for the premature commit.  It's just a stub but should compile now

On 06/14/2016 03:42 AM, Jeff Thompson wrote:
> The methods in Prenexifier have a return type for Formula, but are
> missing return statements. My Java compiler won't compile it. (I'd offer
> a pull request, but I don't know what it's supposed to do.)
> https://github.com/ontologyportal/sigmakee/blob/master/src/java/com/articulate/sigma/Prenexifier.java
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ontologyportal/sigmakee/issues/9>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ACBvHaYOlz1PlOpsDBkimEoK_xZiCVdRks5qLoWOgaJpZM4I1L-7>.
>

-- 
-------------------
Adam Pease
http://www.ontologyportal.org
http://www.articulatesoftware.com
http://www.adampease.org

**Comment by jefft0** [comment]
Thanks for the fixes. Compiling well on Windows now.
